---
regions:
  - "eu-west-1"
account-blacklist:
- 1234567890

accounts:
  555133742:
    filters:
      IAMRole:
      - "uber.admin"
      IAMRolePolicyAttachment:
      - "uber.admin -> AdministratorAccess"
